version: '3.9'

services:
  ib_db:
    container_name: ib_db
    image: postgres:12
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ib
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: {}